spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/semplify
    username: semplify
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    generate-ddl: true

  codec:
    max-in-memory-size: "500MB"

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  security:
    public-key: ${SEMPLIFY_APP_SECURITY_PUBLICKEY}
    token-prefix: Bearer


poolparty:
  host: dl0475odhub006.nsw.education
  port: 80
  username: poolparty
  password: password
  projectId: 1E2601F1-B5C8-0001-164D-C9001170CFD0

spotlight:
  host: localhost
  port: 10000
