spring:
  datasource:
    url: jdbc:postgresql://postgresql:5433/semplify
    username: semplify
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    generate-ddl: true

  codec:
    max-in-memory-size: "500MB"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:9000/auth/realms/semplify/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"





