spring:
  datasource:
    url: jdbc:postgresql://postgresql:5433/semplify
    username: semplify
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    generate-ddl: true

  codec:
    max-in-memory-size: "500MB"

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  security:
    public-key: ${SEMPLIFY_APP_SECURITY_PUBLICKEY}
    token-prefix: Bearer





