spring:
  datasource:
    url: jdbc:postgresql://postgresql:5433/semplify
    username: semplify
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    generate-ddl: true
  redis:
    host: redis
    port: 6379

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  codec:
    max-in-memory-size: "500MB"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:9000/auth/realms/semplify/protocol/openid-connect/certs
      client:
        registration:
          semplify-app:
            provider: keycloak
            client-id: semplify-app
            authorizationGrantType: authorization_code
        provider:
          keycloak:
            issuer-uri: http://keycloak:9000/auth/realms/semplify
            authorization-uri: http://keycloak:9000/auth/realms/semplify/protocol/openid-connect/auth
            token-uri: http://keycloak:9000/auth/realms/semplify/protocol/openid-connect/token
            user-info-uri: http://keycloak:9000/auth/realms/semplify/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:9000/auth/realms/semplify/protocol/openid-connect/certs
            user-name-attribute: preferred_username


management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

spotlight:
  host: spotlight
  port: 11001

poolparty:
  host: poolparty
  port: 80
  username: poolparty
  password: password
  projectId: 1E2601F1-B5C8-0001-164D-C9001170CFD0

app:
  sparql:
    url: http://virtuoso:8890/sparql/
    auth: true
    username: dba
    password: dba

  proxy:
    host: proxy.det.nsw.edu.au
    port: 80

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway: DEBUG