server:
  port: 8951

spring:
  batch:
    job:
      enabled: false

dbpediaspotlight:
  host: localhost
  port: 10000

poolparty:
  host: localhost
  port: 80
  user: poolparty
  password: password
  projectId: 1E14BE74-FD54-0001-663C-F0601ECA1220