spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: elasticsearch:9200
      cluster-nodes: elasticsearch:9200
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200

app:
  crawler:
    numberOfCrawlers: 4
    tmp: "/tmp/crawler4j"